# Generated by Django 5.1.3 on 2025-01-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articolo_visualizzazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
