# Generated by Django 5.1.3 on 2025-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_giornalista_anno_di_nascita'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
